name: build and push image to quay

on:
  release:
    types: [created]
jobs:
  build-push-image:
    runs-on: ubuntu-latest
    steps:
      - uses: crazy-max/ghaction-dump-context@v1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Quay.io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_DOCKER_REGISTRY_USER }}
          password: ${{ secrets.QUAY_DOCKER_REGISTRY_PASSWORD }}
      - name: Get tags
        id: get-tags
        shell: bash
        env:
          TAG_VERSIONS: latest,${{ github.event.release.tag_name }}
        run: |
          fullTags=""
          for version in ${TAG_VERSIONS//,/ }; do
            # trim "v" from tag if it exists
            if [[ $version =~ ^v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+ ]]; then
                trimmedVersion="${version:1}"
                echo "modified $version to $trimmedVersion"
                version=$trimmedVersion
            fi
            # build list of tags with quay registry, use ${blah,,} to ensure lower case
            fullTags="quay.io/catalystsquad/${{ github.event.repository.name }}:$version,$fullTags"
          done
          fullTags=${fullTags::-1}
          echo "will push with tags: $fullTags"
          echo "::set-output name=tags::$fullTags"
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ steps.get-tags.outputs.tags }}